- name: functions
  hosts: local
  connection: local
  vars:
   technologies: DevOps,Linux,Ansible,AWS
   name: chinna reddy
   gmail: "Chinna@gmail.com"
  tasks:
   - name: print the name in upper case
     ansible.builtin.debug:
      msg: "Name of the person: {{ name | upper }}"
   - name: print the gmail in lower
     ansible.builtin.debug:
      msg: "gmail is: {{ gmail | lower }}"   
   # convert string to list using split function
   - name: convert string to list 
     ansible.builtin.debug:
      msg: "the technologies are {{ technologies | split(',') }}" 
        
   - name: grep for root
    #ansible.builtin.command: cat /etc/passwd | grep root
     ansible.builtin.shell: cat /etc/passwd | grep root
     register: command_output

   - name: print the command_output
     ansible.builtin.debug:
      msg: "{{ command_output }}"         