# - name: loops
#   hosts: local
#   connection: local
#   tasks:
#   - name: print the names
#     ansible.builtin.debug:
#      msg: "Hello {{ item }}, welcome to DevOps Course"
#     loop:
#     - "Ramesh"
#     - "suresh"
#     - "chinna"
#     - "Deepak"

# - name: install packages
#   hosts: local
#   connection: local
#   become: yes
#   tasks:
#   - name: installing packages
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: latest
#     loop:
#     - nginx
#     - mysql   

- name: install packages 
  hosts: local
  connection: local
  tasks:
   - name: print installed packages
     ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
     loop:
     - { name: "nginx", state: "absent"}
     - { name: "mysql", state: "absent"}
     - { name: "zip", state: "latest"}    