- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print the names
    ansible.builtin.debug:
     msg: "Hello {{ item }}, welcome to DevOps Course"
    loop:
    - "Ramesh"
    - "suresh"
    - "chinna"
    - "Deepak" 