- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: course info 
    ansible.builtin.debug:
     msg: " The course name is {{ course }}, course duration {{ duration }} and the trainer is {{ trainer }}" 