- name: variables from args
  hosts: local
  connection: local
  tasks:
  - name: course info
    ansible.builtin.debug:
     msg: " The name of the course is {{ course}}, duration{{ duration }} and trainer is {{ trainer}}"